version: '3'
services:
  app:
    build: .
    container_name: app-prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    volumes:
      - ./config/application-prod.yml:/app/config/application.yml
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: prod_db
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: prod_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
