spring:
  application:
    name : testeVRBeneficios
  banner:
    location: banner.txt
  datasource:
    url: jdbc:mysql://db:3306/prod_db
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration